"""Clean causal workflow for wetland connectivity and runoff-depth outcomes.

This script intentionally separates:
  1. descriptive cross-sectional OLS, which is useful but not causal; from
  2. within-gauge causal designs: two-way fixed effects, lagged two-way fixed
     effects, and first differences.

With the current LCMAP-based wetland series, W has essentially no within-gauge
variation, so the clean causal estimators are expected to be unidentified. This
is a feature, not a bug: the report makes the identification failure explicit and
creates an Annual-NLCD-ready panel file for the next data upgrade.
"""
from __future__ import annotations

import argparse
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from linearmodels.panel import PanelOLS

warnings.filterwarnings("ignore")

ROOT = Path("/Users/jared/Wetland")
OUT = ROOT / "outputs" / "sensors"
PANEL_IN = OUT / "panel_matched_depth.csv"
PANEL_OUT = OUT / "panel_causal_ready.csv"
REPORT_OUT = OUT / "clean_causal_report.txt"

OUTCOMES = [
    ("ln_peak", "Flood peak"),
    ("ln_base", "Baseflow"),
    ("ln_total", "Annual total"),
]

WITHIN_SD_MIN = 1e-4
EVENT_DW_THRESHOLD = 0.005  # 0.5 percentage point change in W


def stars(p: float) -> str:
    if p < 0.01:
        return "***"
    if p < 0.05:
        return "**"
    if p < 0.10:
        return "*"
    return ""


def fmt_coef(coef: float, se: float, p: float) -> str:
    return f"{coef:+10.4f}{stars(p):3s}  ({se:9.4f})  p={p:6.3f}"


def within_sd(df: pd.DataFrame, col: str) -> float:
    return float(df[col].sub(df.groupby("site_no")[col].transform("mean")).std())


def between_sd(df: pd.DataFrame, col: str) -> float:
    return float(df.groupby("site_no")[col].mean().std())


def identify_variation(df: pd.DataFrame, variables: list[str]) -> pd.DataFrame:
    rows = []
    for v in variables:
        b = between_sd(df, v)
        w = within_sd(df, v)
        denom = b**2 + w**2
        rows.append(
            {
                "var": v,
                "between_sd": b,
                "within_sd": w,
                "within_share": np.nan if denom == 0 else w**2 / denom,
            }
        )
    return pd.DataFrame(rows)


def load_panel(panel_out: Path) -> pd.DataFrame:
    p = pd.read_csv(PANEL_IN, dtype={"site_no": str})
    p["site_no"] = p["site_no"].str.zfill(8)
    p["year"] = p["year"].astype(int)

    rename = {"Wfrac_exp": "W", "developed_frac": "urban"}
    p = p.rename(columns=rename)

    # Be robust to panel files generated by older scripts.
    if "peak" not in p:
        p["peak"] = p["annual_max_runoff_depth_mm_day"]
    if "base" not in p:
        p["base"] = p["annual_median_runoff_depth_mm_day"]
    if "total" not in p:
        p["total"] = p["annual_total_runoff_depth_mm"]
    if "ln_peak" not in p:
        p["ln_peak"] = np.log(p["peak"].clip(lower=1e-3))
    if "ln_base" not in p:
        p["ln_base"] = np.log(p["base"].clip(lower=1e-3))
    if "ln_total" not in p:
        p["ln_total"] = np.log(p["total"].clip(lower=1e-1))
    if "area" not in p:
        p["area"] = p.get("drainage_area_sqmi")

    required = [
        "site_no",
        "year",
        "W",
        "urban",
        "precip",
        "area",
        "ln_peak",
        "ln_base",
        "ln_total",
    ]
    p = p.dropna(subset=required).sort_values(["site_no", "year"]).copy()

    for v in ["W", "urban", "precip"]:
        p[f"{v}_lag1"] = p.groupby("site_no")[v].shift(1)
        p[f"d_{v}"] = p.groupby("site_no")[v].diff()

    for yv, _ in OUTCOMES:
        p[f"{yv}_lag1"] = p.groupby("site_no")[yv].shift(1)
        p[f"d_{yv}"] = p.groupby("site_no")[yv].diff()

    p["prev_year"] = p.groupby("site_no")["year"].shift(1)
    p["consecutive"] = p["year"].eq(p["prev_year"] + 1)
    p.to_csv(panel_out, index=False)
    return p


def fit_ols(df: pd.DataFrame, yv: str, include_urban: bool = True):
    rhs = "W + precip + Dam + area"
    if include_urban:
        rhs = "W + precip + urban + Dam + area"
    return smf.ols(f"{yv} ~ {rhs}", df).fit(
        cov_type="cluster", cov_kwds={"groups": df["site_no"]}
    )


def fit_twoway(df: pd.DataFrame, yv: str, lagged: bool = False, include_urban: bool = True):
    if lagged:
        subset = [yv, "W_lag1", "precip"]
        rhs = "W_lag1 + precip"
        if include_urban:
            subset.append("urban_lag1")
            rhs += " + urban_lag1"
        d = df.dropna(subset=subset).copy()
        pp = d.set_index(["site_no", "year"])
        formula = f"{yv} ~ 1 + {rhs} + EntityEffects + TimeEffects"
        return d, PanelOLS.from_formula(formula, pp).fit(
            cov_type="clustered", cluster_entity=True
        )

    subset = [yv, "W", "precip"]
    rhs = "W + precip"
    if include_urban:
        subset.append("urban")
        rhs += " + urban"
    d = df.dropna(subset=subset).copy()
    pp = d.set_index(["site_no", "year"])
    formula = f"{yv} ~ 1 + {rhs} + EntityEffects + TimeEffects"
    return d, PanelOLS.from_formula(formula, pp).fit(
        cov_type="clustered", cluster_entity=True
    )


def fit_first_difference(df: pd.DataFrame, yv: str, include_urban: bool = True):
    dy = f"d_{yv}"
    subset = [dy, "d_W", "d_precip"]
    rhs = "d_W + d_precip"
    if include_urban:
        subset.append("d_urban")
        rhs += " + d_urban"
    d = df[df["consecutive"]].dropna(subset=subset).copy()
    if d.empty:
        return d, None
    model = smf.ols(f"{dy} ~ {rhs} + C(year)", d).fit(
        cov_type="cluster", cov_kwds={"groups": d["site_no"]}
    )
    return d, model


def write_report(
    p: pd.DataFrame,
    report_out: Path,
    include_urban: bool = True,
) -> str:
    lines: list[str] = []
    add = lines.append

    vtab = identify_variation(p, ["W", "urban", "precip", "ln_peak"])
    w_within = within_sd(p, "W")

    add("=" * 96)
    suffix = "" if include_urban else " — URBANIZATION DROPPED"
    add(f"CLEAN CAUSAL WORKFLOW{suffix} — wetland connectivity and annual runoff depth")
    add("=" * 96)
    add(
        f"Panel: {len(p)} gauge-years, {p.site_no.nunique()} gauges, "
        f"{int(p.year.min())}-{int(p.year.max())}; unbalanced."
    )
    add("Outcome focus: log annual flood-peak runoff depth, plus baseflow and annual total.")
    add("W = travel-time-weighted wetland fraction.")
    add("")

    add("[1] Identification check: where does variation come from?")
    add(vtab.to_string(index=False, float_format=lambda x: f"{x:0.6f}"))
    if w_within < WITHIN_SD_MIN:
        add(
            "VERDICT: W has effectively zero within-gauge variation. "
            "Clean within-gauge causal effects are NOT identified with the current W series."
        )
    else:
        add(
            "VERDICT: W has usable within-gauge variation. TWFE / first-difference estimates "
            "can be interpreted as within-basin causal designs, subject to assumptions."
        )
    add("")

    add("[2] Descriptive benchmark: pooled OLS (NOT a causal estimate)")
    add("Controls: precip + Dam + area" + (" + urban" if include_urban else "  [urban dropped]"))
    for yv, label in OUTCOMES:
        m = fit_ols(p, yv, include_urban=include_urban)
        add(
            f"{label:14s}  W = "
            f"{fmt_coef(m.params['W'], m.bse['W'], m.pvalues['W'])}  "
            f"N={int(m.nobs):3d}  R2={m.rsquared:0.3f}"
        )
    add("Interpretation: useful cross-sectional association only; basin fixed confounders remain.")
    add("")

    add("[3] Cleaner model A: two-way fixed effects, contemporaneous W")
    if include_urban:
        add("Model: Y_it = beta W_it + rain_it + urban_it + gauge FE + year FE + error_it")
    else:
        add("Model: Y_it = beta W_it + rain_it + gauge FE + year FE + error_it")
    for yv, label in OUTCOMES:
        d, m = fit_twoway(p, yv, lagged=False, include_urban=include_urban)
        add(
            f"{label:14s}  W = "
            f"{fmt_coef(m.params['W'], m.std_errors['W'], m.pvalues['W'])}  "
            f"N={int(m.nobs):3d}  within_R2={m.rsquared_within:0.3f}"
        )
    if w_within < WITHIN_SD_MIN:
        add("Identification note: ignore the W point estimates above; they are numerical noise.")
    add("")

    add("[4] Cleaner model B: lagged two-way fixed effects")
    if include_urban:
        add("Model: Y_it = beta W_i,t-1 + rain_it + urban_i,t-1 + gauge FE + year FE + error_it")
    else:
        add("Model: Y_it = beta W_i,t-1 + rain_it + gauge FE + year FE + error_it")
    lag = p.dropna(subset=["W_lag1"])
    lag_w_within = within_sd(lag, "W_lag1") if len(lag) else np.nan
    add(f"Lagged-W within-gauge SD = {lag_w_within:0.6f}")
    for yv, label in OUTCOMES:
        d, m = fit_twoway(p, yv, lagged=True, include_urban=include_urban)
        add(
            f"{label:14s}  W_lag1 = "
            f"{fmt_coef(m.params['W_lag1'], m.std_errors['W_lag1'], m.pvalues['W_lag1'])}  "
            f"N={int(m.nobs):3d}  within_R2={m.rsquared_within:0.3f}"
        )
    if lag_w_within < WITHIN_SD_MIN:
        add("Identification note: lagging W does not solve the current LCMAP flat-W problem.")
    add("")

    add("[5] Cleaner model C: first differences on consecutive years")
    if include_urban:
        add("Model: dY_it = beta dW_it + dRain_it + dUrban_it + year FE + error_it")
    else:
        add("Model: dY_it = beta dW_it + dRain_it + year FE + error_it")
    fd = p[p["consecutive"]].dropna(subset=["d_W"])
    add(
        f"Consecutive-year rows: {len(fd)}; dW SD = "
        f"{float(fd['d_W'].std()) if len(fd) else np.nan:0.6f}"
    )
    for yv, label in OUTCOMES:
        d, m = fit_first_difference(p, yv, include_urban=include_urban)
        if m is None:
            add(f"{label:14s}  not enough consecutive observations.")
            continue
        add(
            f"{label:14s}  d_W = "
            f"{fmt_coef(m.params['d_W'], m.bse['d_W'], m.pvalues['d_W'])}  "
            f"N={int(m.nobs):3d}  R2={m.rsquared:0.3f}"
        )
    if len(fd) == 0 or fd["d_W"].std() < WITHIN_SD_MIN:
        add("Identification note: first differences also lack dW variation; beta is not credible.")
    add("")

    add("[6] Event-study readiness")
    events = fd.loc[fd["d_W"].abs() >= EVENT_DW_THRESHOLD, ["site_no", "year", "d_W"]]
    add(
        f"Potential wetland-change events using |dW| >= {EVENT_DW_THRESHOLD:0.3f}: "
        f"{len(events)} rows across {events.site_no.nunique() if len(events) else 0} gauges."
    )
    if len(events):
        add(events.sort_values("d_W", key=lambda s: s.abs(), ascending=False).head(20).to_string(index=False))
    else:
        add("No usable events found. An Annual-NLCD-based W is needed for event-study / DiD.")
    add("")

    add("[7] Recommended next data/workflow change")
    add("Replace the current LCMAP wetland series with Annual NLCD 1985-2023 classes 90+95.")
    add("Then recompute W_it using the existing travel-time rasters T_{site}.tif, rerun this script,")
    add("and use section [3]/[4]/[5] as the main causal results. OLS should remain descriptive.")

    report = "\n".join(lines) + "\n"
    report_out.write_text(report)
    return report


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--drop-urban",
        action="store_true",
        help="Drop urban/developed fraction from all regression specifications.",
    )
    args = ap.parse_args()

    if args.drop_urban:
        panel_out = OUT / "panel_causal_ready_no_urban.csv"
        report_out = OUT / "clean_causal_no_urban_report.txt"
    else:
        panel_out = PANEL_OUT
        report_out = REPORT_OUT

    p = load_panel(panel_out)
    report = write_report(p, report_out, include_urban=not args.drop_urban)
    print(report)
    print(f"Wrote: {panel_out}")
    print(f"Wrote: {report_out}")


if __name__ == "__main__":
    main()
